spring:
  application:
    name: mfa-server
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mfa-server
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail
    password: yourpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
