spring:
  application:
    name: mfa-server
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mfa-server
  mail:
    host: smtp.gmail.com
    port: 587
    username: anbuathypathy@gmail.com
    password: "sptp ettc qjiv xegx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true